name: NixOS build and deploy config

on:
  workflow_dispatch:
  # We cannot include the paths-ignore part here because this check is set as
  # required for PRs. Otherwise the PR cannot be merged when this workflow does
  # not run.
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - 'install.sh'
      - 'README.md'
      - '.gitignore'

jobs:

  shared:
    uses: 'msf-ocb/nixos/.github/workflows/reusable_build_deploy.yml@master'
    with:
      push_secrets:    false
      push_robot_keys: false
    secrets:
      NIXOS_OCB_CONFIG_DEPLOY_KEY: ${{ secrets.NIXOS_OCB_CONFIG_DEPLOY_KEY }}
      NIXOS_OCB_KEY_MGMT_API_TOKEN: ${{ secrets.NIXOS_OCB_KEY_MGMT_API_TOKEN }}
      NIXOS_ROBOT_KEY: ${{ secrets.NIXOS_ROBOT_KEY }}
      NIXOS_SECRET_MANAGEMENT_VAULT_KEY: ${{ secrets.NIXOS_SECRET_MANAGEMENT_VAULT_KEY }}

